// Export selected default bags
export const defaultBags = [
  {
    id: 4,
    attributes: [ 
      'holographic hash',
      'crusty grav',
      'cosmic brownie',
      'OJ',
      'lighter of power',
      'cup ramen',
      'birkenstocks',
      'lunchables',
      'shatter',
      'mythic shatter',
      'elite dryer sheet',
      'half eighth',
      'secret resin',
      'divine lighter',
      'crusty bubble water',
      'trichomes of paranoia' 
    ],
  },
  {
    id: 42,
    attributes: [ 'shatter of the 3rd dimension',
    'gas station backwood',
    'humus',
    'Milkshake',
    'scale',
    'kit-kat',
    'febreze of old' ],
  },
  {
    id: 420,
    attributes: [ 'holy dime',
    'dutchmaster',
    'ice cream',
    'faygo',
    'grinder',
    'ice cream',
    'snuggy of exauhstion',
    'sour starburst of exauhstion',
    'wax',
    'BC\'s' ],
  },
  {
    id: 6969,
    attributes: [ 'quarter of rage',
    'hot box',
    'older sisters EZ Mac',
    'Arizona Tea',
    'snuggy',
    'cheeto dust',
    'febreze of paranoia',
    'kit-kat',
    'BC\'s of the 3rd dimension',
    'beasters',
    'incense' ],
  },
  {
    id: 1234,
    attributes: [ 'half eighth',
    'knife hit',
    'stale club crackers',
    'vanilla cola',
    'hoodie',
    'older sisters soggy taco',
    'tie dye',
    'tortilla chip',
    'beasters',
    'Fossilized beasters',
    'tweezers',
    'ounce',
    'shatter of paranoia',
    'ash tray' ],
  }
];
